### PR TITLE
Config gui lists

### LINKED ISSUE #1: Implement TypeProvider for lists
Another provider must be registered in `DefaultGuiProviders`. Right now, it can use the existing Cloth Config lists:

```
    IntListBuilder startIntList(String var1, List<Integer> var2);

    LongListBuilder startLongList(String var1, List<Long> var2);

    FloatListBuilder startFloatList(String var1, List<Float> var2);

    DoubleListBuilder startDoubleList(String var1, List<Double> var2);

    StringListBuilder startStrList(String var1, List<String> var2);
```

I hope to add support for object lists in the future.

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #1 

The base branch might need to be changed if you want to stay with the versioned branches.

~~Blocked by https://github.com/shedaniel/ClothConfig/issues/21~~

### CODE REVIEW

**Comment by shedaniel** [comment]
I don't think we want versioned branches _yet_, as the current version works on both versions, I will change the base branch when this is merged or something.

**Comment by magneticflux-** [comment]
Okay! This _should_ still work on 1.14 versions as long as there is a compatible version of `me.shedaniel.cloth:config-2`.

**Comment by shedaniel** [comment]
Don't worry! We will just **force** everyone on 1.15 sometime in the future.

**Comment by shedaniel** [comment]
If this should be merged, please tell me, thanks!

**Comment by magneticflux-** [comment]
It works after my latest commit https://github.com/shedaniel/AutoConfig/pull/2/commits/9fa9b3bac5c7655cd8af2000911bb66e060e00d2, but it could definitely be cleaner. I think that could just be saved for a rewrite though, it's probably not worth it right now.

Classes have started up now so my time to work on this is more limited, but I still want to contribute.

**Comment by shedaniel** [comment]
I will probably merge this soon because this is a nice feature, the rewrite can happen but I have no idea when I will do it

**Comment by shedaniel** [comment]
Thank you! I have added this

**Pull request closed without merging**
